### ISSUE TITLE
Own Estimate Food is not submitted and Sum of total Calculation

### ISSUE THREAD

**Issue by pankeshpatel** [pankeshpatel/mDiabetes#10]
[Screenshot](https://github.com/pankeshpatel/mDiabetes/blob/881f5326c4dbbcc486e0b9d0cb70d6d06d324cee/img/own-estimate-total-submit.png)

**Comment by pankeshpatel** [comment]
Bug

**Comment by pankeshpatel** [comment]
Bug found

**Comment by pankeshpatel** [comment]
Own. estimation value has not been submitted to the "history and Alartms".

Please fix it. @JINU98

**Comment by JINU98** [comment]
This issue is also fixed please check

**Comment by pankeshpatel** [comment]
Thanks, @JINU98 for fixing this bug!
