### ISSUE TITLE
"With Camera" button remains disabled, before selecting meal type

### ISSUE THREAD

**Issue by pankeshpatel** [pankeshpatel/mDiabetes#14]
"With Camera" button remains disabled, before selecting meal type

See the screenshot @JINU98 

[Disable Button](https://github.com/pankeshpatel/mDiabetes/blob/4d1e16d9ef402b3a6d9137259831360d4f7e841b/img/disable-button.png)

@JINU98 : Please fix this.
Either "Disable Both Screens" OR "enable both screens"

**Comment by JINU98** [comment]
This is fixed please check

**Comment by pankeshpatel** [comment]
Thanks, @JINU98 for fixing this bug!
